version: "3"
services:
  mkdocs:
    image: python:3.8-buster
    container_name: mkdocs
    tty: true
    ports:
      - "0.0.0.0:8888:8000"
    working_dir: /docs
    volumes:
      - .:/docs
    command: >
      sh -c "pip install -r requirements &&
            git config --global --add safe.directory /docs &&
            mkdocs serve"
