version: '3'
services:
  #NODE Service
  app:
    image: node:${NODE_V}
    tty: true
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 4443:3000
      #- ${SERVER_PORT}:3000
    networks:
      - app-network

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - app-network
    #ports:
    #  - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ##Password to use the aplicaction
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
      ##Connection DATA (user,pas,etc) to the DB
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
    depends_on:
      - mongodb
    networks:
      - app-network
    ports:
      - 8081:8081  
 
#Docker Networks
networks:
  app-network:
    driver: bridge
