FROM nginx:latest

LABEL maintainer="Carlos Jimenez"

COPY index.html /usr/share/nginx/html/
COPY 2.html /usr/share/nginx/html/
COPY 3.html /usr/share/nginx/html/
COPY 403.html /usr/share/nginx/html/
COPY 404.html /usr/share/nginx/html/

RUN apt-get update && \
    apt-get install -y nano && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]