version: '3'
services:
  #PHP Service
  php:
    image: php:7.4-fpm
    entrypoint: bash /scripts/init.sh
    working_dir: /app
    tty: true
    volumes:
      - ./app:/app
      - ./conf/php/init.sh:/scripts/init.sh
      - ./conf/php/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      lan:
        aliases:
         - php-server

  ##Nginx Service
  nginx:
    image: nginx:alpine
    working_dir: /app
    tty: true
    ports:
      - ${WEB_PORT}:80
      - ${SECURE_PORT}:443
    volumes:
      - ./app:/app
      - ./logs/:/var/log/nginx/
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on: 
      - php
    networks:
      - lan

#Docker Networks
networks:
  lan:
    driver: bridge
