version: '3'
services:
  #PHP Service
  php-fpm:
    image: php:7.4-fpm
    hostname: php-server
    restart: unless-stopped
    entrypoint: bash /scripts/init.sh
    working_dir: /app
    tty: true
    volumes:
      - ./app:/app
      - ./docker/php/init.sh:/scripts/init.sh
      - ./docker/php/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  ##Nginx Service
  nginx:
    image: nginx:alpine
    working_dir: /app
    tty: true
    ports:
      - ${WEB_PORT}:80
      - ${SECURE_PORT}:443
    volumes:
      - ./app:/app
      - ./docker/logs/:/var/log/nginx/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on: 
      - php-fpm
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
